msm: kgsl_ioctl: Fix Compile Error
../drivers/gpu/msm/kgsl_ioctl.c:210:18: error: initializing 'unsigned long' with an expression of incompatible type 'struct cpumask'
                .cpus_affine = qos_cpus,
                               ^~~~~~~~
1 error generated.
make[4]: *** [../scripts/Makefile.build:338: drivers/gpu/msm/kgsl_ioctl.o] Error 1
make[3]: *** [../scripts/Makefile.build:642: drivers/gpu/msm] Error 2
make[2]: *** [../scripts/Makefile.build:642: drivers/gpu] Error 2
make[1]: *** [/__w/builder-xobod-r/builder-xobod-r/kernel/Makefile:1220: drivers] Error 2

* Error happened after picked this commit ef00dfe8b381e159b919c61377d5cc3c579f1d86.

Fixes: a5d587fdbd56996d0b2c82ad9be9687518e2528b ("msm: kgsl: Reduce latency while processing ioctls")
Signed-off-by: RyuujiX <saputradenny712@gmail.com>